# Este flujo de trabajo compilará un proyecto Java con Maven, almacenará en caché/restaurará las dependencias y ejecutará las pruebas ubicadas en src/test/java/org/example
# Para obtener más información, consulte: https://docs.github.com/es/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# Este flujo de trabajo utiliza acciones que no están certificadas por GitHub.
# Son proporcionadas por un tercero y se rigen por
# términos de servicio, políticas de privacidad y documentación de soporte independientes.

name: CI de Java con Maven y pruebas

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compilar-y-probar:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Instalar dependencias de Maven (caché)
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            - ${{ runner.os }}-maven-

      - name: Compilar con Maven
        run: mvn test

